# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.srcpath = QtWidgets.QTextEdit(self.centralwidget)
        self.srcpath.setGeometry(QtCore.QRect(110, 50, 361, 31))
        self.srcpath.setObjectName("srcpath")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 40, 161, 41))
        self.label1.setObjectName("label1")
        self.browse1 = QtWidgets.QPushButton(self.centralwidget)
        self.browse1.setGeometry(QtCore.QRect(490, 50, 75, 23))
        self.browse1.setObjectName("browse1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(10, 80, 161, 41))
        self.label2.setObjectName("label2")
        self.browse2 = QtWidgets.QPushButton(self.centralwidget)
        self.browse2.setGeometry(QtCore.QRect(490, 90, 75, 23))
        self.browse2.setObjectName("browse2")
        self.destpath = QtWidgets.QTextEdit(self.centralwidget)
        self.destpath.setGeometry(QtCore.QRect(110, 90, 361, 31))
        self.destpath.setObjectName("destpath")
        self.textfile = QtWidgets.QTextEdit(self.centralwidget)
        self.textfile.setGeometry(QtCore.QRect(110, 130, 361, 31))
        self.textfile.setObjectName("textfile")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(10, 120, 161, 41))
        self.label3.setObjectName("label3")
        self.browse3 = QtWidgets.QPushButton(self.centralwidget)
        self.browse3.setGeometry(QtCore.QRect(490, 130, 75, 23))
        self.browse3.setObjectName("browse3")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(380, 220, 81, 31))
        self.ok.setAutoFillBackground(False)
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(480, 220, 81, 31))
        self.cancel.setObjectName("cancel")
        self.successmsg = QtWidgets.QLabel(self.centralwidget)
        self.successmsg.setGeometry(QtCore.QRect(220, 170, 161, 41))
        self.successmsg.setText("")
        self.successmsg.setObjectName("successmsg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.srcpath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label1.setText(_translate("MainWindow", "Source Folder:"))
        self.browse1.setText(_translate("MainWindow", "Browse"))
        self.label2.setText(_translate("MainWindow", "Destination Folder:"))
        self.browse2.setText(_translate("MainWindow", "Browse"))
        self.destpath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textfile.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label3.setText(_translate("MainWindow", "Images List:"))
        self.browse3.setText(_translate("MainWindow", "Browse"))
        self.ok.setText(_translate("MainWindow", "Move Files"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
